"""
Mutation testing engine.

Measures test quality by generating mutants (small code changes) and checking
which agents' tests can detect ("kill") them.

Two mutation sources:
    1. cosmic-ray operators — operator swaps, constant tweaks, boolean flips, etc.,
       using cosmic-ray's parso-based AST mutation operators (Windows-compatible).
    2. LLM mutants — semantically realistic bugs generated by the mutate agent.

run_all_agents(func_file, test_files_dict, repo_clone_dir, source, original_file)
    Generates all mutants once, then tests every (agent, mutant) combination
    in parallel using a single ProcessPoolExecutor. Returns:
        agent_kills   — dict[test_type -> set of mutant IDs killed]
        agent_totals  — dict[test_type -> total mutant count]
        mutant_count  — total number of mutants generated

compute_unique_kills(agent_kills)
    For each agent, counts mutants that ONLY that agent kills — its unique contribution.
"""
import ast
import concurrent.futures
import copy
import json
import os
import shutil
import subprocess
import sys
import tempfile


DEFAULT_CUSTOM_MUTANT_TIMEOUT = 10


def _generate_mutants(source):
    import parso
    from cosmic_ray.operators.binary_operator_replacement import (
        ReplaceBinaryOperator_Add_Sub, ReplaceBinaryOperator_Sub_Add,
        ReplaceBinaryOperator_Mul_Div, ReplaceBinaryOperator_Div_Mul,
        ReplaceBinaryOperator_FloorDiv_Div, ReplaceBinaryOperator_Mod_Mul,
    )
    from cosmic_ray.operators.comparison_operator_replacement import (
        ReplaceComparisonOperator_Lt_LtE, ReplaceComparisonOperator_LtE_Lt,
        ReplaceComparisonOperator_Gt_GtE, ReplaceComparisonOperator_GtE_Gt,
        ReplaceComparisonOperator_Eq_NotEq, ReplaceComparisonOperator_NotEq_Eq,
        ReplaceComparisonOperator_Is_IsNot, ReplaceComparisonOperator_IsNot_Is,
    )
    from cosmic_ray.operators.boolean_replacer import (
        ReplaceAndWithOr, ReplaceOrWithAnd, ReplaceTrueWithFalse, ReplaceFalseWithTrue, AddNot,
    )
    from cosmic_ray.operators.break_continue import ReplaceBreakWithContinue, ReplaceContinueWithBreak
    from cosmic_ray.operators.number_replacer import NumberReplacer
    from cosmic_ray.operators.unary_operator_replacement import (
        ReplaceUnaryOperator_USub_UAdd, ReplaceUnaryOperator_UAdd_USub,
    )
    from cosmic_ray.operators.zero_iteration_for_loop import ZeroIterationForLoop

    cr_operators = [
        ("arith_swap", ReplaceBinaryOperator_Add_Sub()),
        ("arith_swap", ReplaceBinaryOperator_Sub_Add()),
        ("arith_swap", ReplaceBinaryOperator_Mul_Div()),
        ("arith_swap", ReplaceBinaryOperator_Div_Mul()),
        ("arith_swap", ReplaceBinaryOperator_FloorDiv_Div()),
        ("arith_swap", ReplaceBinaryOperator_Mod_Mul()),
        ("cmp_swap", ReplaceComparisonOperator_Lt_LtE()),
        ("cmp_swap", ReplaceComparisonOperator_LtE_Lt()),
        ("cmp_swap", ReplaceComparisonOperator_Gt_GtE()),
        ("cmp_swap", ReplaceComparisonOperator_GtE_Gt()),
        ("cmp_swap", ReplaceComparisonOperator_Eq_NotEq()),
        ("cmp_swap", ReplaceComparisonOperator_NotEq_Eq()),
        ("cmp_swap", ReplaceComparisonOperator_Is_IsNot()),
        ("cmp_swap", ReplaceComparisonOperator_IsNot_Is()),
        ("bool_swap", ReplaceAndWithOr()),
        ("bool_swap", ReplaceOrWithAnd()),
        ("bool_swap", ReplaceTrueWithFalse()),
        ("bool_swap", ReplaceFalseWithTrue()),
        ("cond_neg", AddNot()),
        ("break_continue", ReplaceBreakWithContinue()),
        ("break_continue", ReplaceContinueWithBreak()),
        ("num_replace", NumberReplacer()),
        ("sign_flip", ReplaceUnaryOperator_USub_UAdd()),
        ("sign_flip", ReplaceUnaryOperator_UAdd_USub()),
        ("zero_iter", ZeroIterationForLoop()),
    ]

    mutants = []
    seen_sources = set()

    try:
        parso_tree = parso.parse(source)
    except Exception:
        parso_tree = None

    def walk_parso(node):
        yield node
        if hasattr(node, "children"):
            for child in node.children:
                yield from walk_parso(child)

    if parso_tree is not None:
        for tag, op in cr_operators:
            for node in walk_parso(parso_tree):
                positions = list(op.mutation_positions(node))
                for idx, _ in enumerate(positions):
                    tree_copy = copy.deepcopy(parso_tree)
                    for n2 in walk_parso(tree_copy):
                        if (n2.start_pos == node.start_pos and n2.end_pos == node.end_pos
                                and type(n2) == type(node)):
                            result = op.mutate(n2, idx)
                            if result is not None:
                                mutated_src = tree_copy.get_code()
                                if mutated_src != source and mutated_src not in seen_sources:
                                    seen_sources.add(mutated_src)
                                    desc = f"{tag} at line {node.start_pos[0]}"
                                    mutants.append((tag, mutated_src, desc))
                            break

    return mutants


def _test_combination(args):
    test_type, mid, mutated_source, test_file, target_file, repo_clone_dir, timeout = args
    env = os.environ.copy()
    env["PYTHONPATH"] = repo_clone_dir + os.pathsep + env.get("PYTHONPATH", "")

    if target_file:
        tmp_dir = tempfile.mkdtemp()
        # Write at full relative path so package imports (e.g. "from algorithms.arrays.X import Y")
        # resolve to the mutated file instead of the original in repo_clone_dir
        rel_path = os.path.relpath(target_file, repo_clone_dir)
        tmp_full = os.path.join(tmp_dir, rel_path)
        os.makedirs(os.path.dirname(tmp_full), exist_ok=True)
        with open(tmp_full, "w", encoding="utf-8") as f:
            f.write(mutated_source)
        # Create __init__.py for all parent directories so the package is importable
        parent = os.path.dirname(rel_path)
        if parent:
            parts = parent.split(os.sep)
            for i in range(1, len(parts) + 1):
                init_file = os.path.join(tmp_dir, *parts[:i], "__init__.py")
                if not os.path.exists(init_file):
                    open(init_file, "w").close()
        # Also write at bare basename for tests that import without the package path
        tmp_base = os.path.join(tmp_dir, os.path.basename(target_file))
        if tmp_base != tmp_full:
            with open(tmp_base, "w", encoding="utf-8") as f:
                f.write(mutated_source)
        env["PYTHONPATH"] = tmp_dir + os.pathsep + env["PYTHONPATH"]
    else:
        tmp_dir = None

    try:
        result = subprocess.run(
            [sys.executable, "-m", "pytest", test_file, "-x", "-q", "--tb=no", "--no-header"],
            capture_output=True, text=True, env=env, timeout=timeout,
        )
        return test_type, mid, result.returncode != 0
    except (subprocess.TimeoutExpired, Exception):
        return test_type, mid, False
    finally:
        if tmp_dir:
            shutil.rmtree(tmp_dir, ignore_errors=True)


def generate_llm_mutants(fn, config):
    from src.agents import call_agent

    raw = call_agent("mutate", fn, config)
    if not raw.strip():
        return []

    # strip markdown fencing if present
    text = raw.strip()
    text = text.replace("```json", "").replace("```", "").strip()

    # find the JSON array
    start = text.find("[")
    end = text.rfind("]")
    if start == -1 or end == -1 or end <= start:
        return []

    try:
        items = json.loads(text[start:end + 1])
    except json.JSONDecodeError:
        return []

    if not isinstance(items, list):
        return []

    mutants = []
    for item in items:
        if not isinstance(item, dict):
            continue
        desc = item.get("description", "")
        source = item.get("mutated_source", "")
        if not desc or not source:
            continue
        # validate it parses
        try:
            ast.parse(source)
        except SyntaxError:
            continue
        mutants.append(("llm_mutant", source, desc))

    return mutants[:10]


def run_all_agents(func_file, test_files_dict, repo_clone_dir, source, original_file=None, fn=None, config=None):
    custom_mutant_timeout = config["timeouts"]["custom_mutant"] if config else DEFAULT_CUSTOM_MUTANT_TIMEOUT
    ast_mutants = _generate_mutants(source)
    agent_kills = {tt: set() for tt in test_files_dict}
    agent_totals = {tt: 0 for tt in test_files_dict}

    # generate LLM mutants if function info available
    llm_mutants = []
    if fn and config:
        try:
            llm_mutants = generate_llm_mutants(fn, config)
            print(f"    [mutator] generated {len(llm_mutants)} LLM mutants")
        except Exception as e:
            print(f"    [mutator] LLM mutant generation failed: {e}")

    all_mutants = ast_mutants + llm_mutants

    mutant_descriptions = [
        {"id": i + 1, "tag": tag, "description": desc}
        for i, (tag, _source, desc) in enumerate(all_mutants)
    ]

    if not all_mutants:
        return agent_kills, agent_totals, 0, []

    if original_file and os.path.exists(original_file):
        target_file = original_file
    else:
        target_file = None

    worker_args = []
    for i, (_tag, mutated_source, _desc) in enumerate(all_mutants):
        mid = i + 1
        for test_type, test_file in test_files_dict.items():
            worker_args.append((test_type, mid, mutated_source, test_file, target_file, repo_clone_dir, custom_mutant_timeout))

    max_workers = min(os.cpu_count() or 4, len(worker_args), 16)
    with concurrent.futures.ProcessPoolExecutor(max_workers=max_workers) as executor:
        futures = {executor.submit(_test_combination, args): args for args in worker_args}
        for future in concurrent.futures.as_completed(futures):
            test_type, mid, was_killed = future.result()
            if was_killed:
                agent_kills[test_type].add(mid)

    for tt in test_files_dict:
        agent_totals[tt] = len(all_mutants)

    return agent_kills, agent_totals, len(all_mutants), mutant_descriptions


def compute_unique_kills(all_agent_kills):
    result = {}
    agents = list(all_agent_kills.keys())
    for agent in agents:
        others = set()
        for other_agent in agents:
            if other_agent != agent:
                others |= all_agent_kills[other_agent]
        unique = all_agent_kills[agent] - others
        result[agent] = len(unique)
    return result
